chore: update READ.md
gitcoinco/grants-round pull request #111
Opened 2022-07-02 06:01 UTC by thelostone-mc

##### Description

Update documentation for gitbook integration

2022-07-05 14:44 UTC, chibie requested changes
lgtm! few typos

2022-07-05 14:49 UTC, thelostone-mc commented on packages/round-manager/README.md
> +- maintaing a program
```suggestion
- maintaining a program
```

2022-07-05 16:03 UTC, merged

2023-04-10 00:31 UTC, Abuchtela commented on README.md
> +│   ├── graph                   # graph which indexes data from contracts
`├── graph # graph which indexes data from contracts`

2023-04-10 00:31 UTC, Abuchtela commented on README.md
> +│   ├── graph                   # graph which indexes data from contracts
```suggestion
│   ├── graph                   # graph which indexes data from contracts
```