Lit
gitcoinco/grants-round pull request #238
Opened 2022-08-03 22:52 UTC by thelostone-mc

##### Description

##### Refers/Fixes

##### Testing

2022-08-04 23:21 UTC, thelostone-mc commented on packages/round-manager/src/features/api/lit.ts
> +      accessControlConditions: this.isRoundOperatorAccessControl(),
Shouldn't this evmContractConditions as well ?

2022-08-08 21:32 UTC, shavinac approved these changes

2022-08-08 21:32 UTC, shavinac commented on packages/round-manager/docs/EncryptingPII.md
> +  contract: "0x22c0e3EDc90f6A890A259130B416Cd5F3Ee4Aca0"
just to make sure i have this right - this address is a round contract, and LIT only decrypts for addresses who are round operators for that particular round?

2022-08-08 22:31 UTC, chibie requested changes
few comments + merge conflicts that need to be resolved

2022-08-08 22:31 UTC, chibie commented on packages/round-manager/src/features/api/lit.ts
> +
can we remove console log comments like these?

2022-08-08 22:31 UTC, chibie commented on packages/round-manager/src/features/api/lit.ts
> +const LitJsSdk = require('lit-js-sdk');
why `require` and not `import`?

2022-08-09 15:06 UTC, chibie commented on packages/round-manager/src/features/api/lit.ts
> +const LitJsSdk = require('lit-js-sdk');
i know why now..

2022-08-09 15:07 UTC, chibie approved these changes

2022-08-09 15:07 UTC, merged