feat: cleaner date picker UX
gitcoinco/grants-round pull request #544
Opened 2022-10-19 16:59 UTC by thelostone-mc

##### Description

- prevent users from picking past dates
- add validation error if application start date is in the past

##### Refers/Fixes

fixes #450

2022-10-19 21:29 UTC, shavinac approved these changes

2022-10-20 07:45 UTC, melissa-neira approved these changes

2022-10-20 11:42 UTC, nfrgosselin requested changes
Overall it looks good, but we're missing the requirement to set the time to a point later than now if you select today as a date

2022-10-20 21:44 UTC, shavinac commented
> Overall it looks good, but we're missing the requirement to set the time to a point later than now if you select today as a date

Addressed in latest push to this PR 👍

2022-10-21 12:23 UTC, nfrgosselin approved these changes

2022-10-21 12:23 UTC, merged