feat: support contact input field
gitcoinco/grants-round pull request #618
Opened 2022-11-04 08:06 UTC by chibie

##### Description

GIVEN that I am on step one of Round Creation
WHEN I look at the page
THEN I see the empty state of the Contact Information field next to Support Input

GIVEN that I am on step one of Round Creation
WHEN I click on the Contact Information field
THEN I can enter text into the field

GIVEN that I have not entered an email or URL in the Contact Information field
WHEN I click next
THEN I see an error message that I must enter contact information

GIVEN that I have entered in a Support Input and Contact Information
WHEN I deploy the round
THEN the information is saved in my round metadata

##### Refers/Fixes

closes #603 

##### Testing

2022-11-04 12:26 UTC, thelostone-mc approved these changes

2022-11-04 14:34 UTC, melissa-neira requested changes
Placeholder text missing, please add. Also, the support input dropdown is missing some extra text next to the "Other" option, see example below
![Create a Round - Empty](https://user-images.githubusercontent.com/87520659/200001062-b7e87408-ab05-4bfb-9a50-190f48e259b1.png)

2022-11-04 14:48 UTC, nfrgosselin commented
Also please update the validation on the "Contact Information" field so that it only accepts emails or URLs

2022-11-08 13:44 UTC, nfrgosselin approved these changes

2022-11-08 14:20 UTC, melissa-neira requested changes
The "other" field is missing the text referenced in the image above. Can you add that, please? Thank you! 💖

2022-11-08 15:03 UTC, melissa-neira approved these changes

2022-11-08 15:04 UTC, merged