Select shortlist
gitcoinco/grants-round pull request #654
Opened 2022-11-10 05:47 UTC by thelostone-mc

##### Description

##### Refers/Fixes

##### Testing

2022-11-10 15:56 UTC, melissa-neira requested changes
Copy on select button (when projects are selected) should read:
![White Button](https://user-images.githubusercontent.com/87520659/201143200-cd118743-1d34-4dba-84d5-4790f6912e97.png) with # of projects selected in parenthesis. 

Currently, it looks like this:
<img width="536" alt="Screen Shot 2022-11-10 at 10 52 24" src="https://user-images.githubusercontent.com/87520659/201142837-ddbf2487-52e9-4ddc-9f34-e3e69152592d.png"> 
(no parenthesis)

2022-11-10 16:46 UTC, nfrgosselin commented
I agree with @melissa-neira's point, otherwise lgtm

2022-11-10 17:14 UTC, vacekj approved these changes

2022-11-10 17:16 UTC, vacekj approved these changes

2022-11-10 17:17 UTC, vacekj approved these changes

2022-11-11 14:19 UTC, nfrgosselin approved these changes

2022-11-11 16:23 UTC, melissa-neira approved these changes

2022-11-11 16:24 UTC, merged