feat: add shortlist button in project cards
gitcoinco/grants-round pull request #719
Opened 2022-11-24 12:34 UTC by bhargavaparoksham

##### Description

As a user
I want to be able to add a project I like to my shortlist
So that I don't have to navigate away from the landing page in order to do so

##### Refers/Fixes

fixes #694 

##### Testing

2022-11-27 18:21 UTC, thelostone-mc approved these changes

2022-11-28 11:45 UTC, melissa-neira requested changes
The grey background behind the add to shortlist button doesn't reflect the design. Check [here](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1583%3A54760&t=5v5za9zy2s3QlKAS-4) for reference. 
The padding on the bottom of the card seems to be a little off as well. There should be 16px between the bottom of the add to shortlist button and the bottom of the card. I'm seeing a bit more padding there currently. lmk if you have any questions! thank you 😎

2022-11-28 15:00 UTC, nfrgosselin approved these changes
The functionality looks good to me — once @melissa-neira's design changes are addressed this is good to go

2022-11-28 15:35 UTC, melissa-neira approved these changes

2022-11-28 15:35 UTC, merged