feat(ge): change shortlist icon
gitcoinco/grants-round pull request #735
Opened 2022-12-02 16:44 UTC by vacekj

fixes #726

2022-12-02 18:33 UTC, bhargavaparoksham requested changes
1. Shortlist icon is not getting updated with the number of projects currently in the Shortlist, when I test it locally.
2. Tests need to be added.

2022-12-02 18:50 UTC, melissa-neira commented
I'm encountering the same issues as @bhargavaparoksham

2022-12-03 15:02 UTC, thelostone-mc commented on packages/grant-explorer/src/features/common/Navbar.tsx
> +            <Shortlist count={0} roundUrlPath={props.roundUrlPath} />
This would probably need to be fetched from `loadShortlist(roundId)` and just do a `.length` to it

2022-12-06 09:58 UTC, chibie submitted a review, later dismissed
@vacekj +1 on aditya's comment

2022-12-07 17:19 UTC, vacekj commented
should be fixed now

2022-12-08 07:23 UTC, vacekj commented
@thelostone-mc @chibie @hmrtn @bhargavaparoksham

2022-12-08 07:46 UTC, bhargavaparoksham commented
@vacekj It still doesn't work as it should. The shortlist count gets updated only if the page is refreshed after adding projects to shortlist.

2022-12-08 07:51 UTC, vacekj commented
Seems like we need a useLocalStorage hook that listens for updates, will fix.

2022-12-08 13:41 UTC, bhargavaparoksham approved these changes

2022-12-08 15:52 UTC, merged