chore: fix etherscan link on thank you page
gitcoinco/grants-round pull request #794
Opened 2022-12-09 15:29 UTC by chibie

##### Description

##### Refers/Fixes

closes #792 

##### Testing

2022-12-09 16:24 UTC, hmrtn approved these changes

2022-12-09 16:28 UTC, thelostone-mc requested changes
Could we just add the mainnet chain ID as well and default to goerli ?
Just to keep this consistent as everyone goerli is the default

2022-12-09 17:59 UTC, bhargavaparoksham commented
The transaction link is redirecting to the mainnet etherscan, but the txHash is undefined, so the link is failing. Note that in metamask the tx is successful.

@chibie @thelostone-mc 

<img width="1440" alt="Screenshot 2022-12-09 at 7 12 58 PM" src="https://user-images.githubusercontent.com/22616592/206764040-a457b27d-f006-4bd9-b2fc-bff30499ef22.png">

2022-12-09 22:42 UTC, nfrgosselin approved these changes

2022-12-10 00:08 UTC, hmrtn commented
The commits here also address the unrelated footer issues across the application - they were a nuisance.

2022-12-10 03:53 UTC, merged