feat(ge): project stats
gitcoinco/grants-round pull request #855
Opened 2022-12-16 15:15 UTC by vacekj

fixes #482 

##### Testing

added tests for the new component

2022-12-23 04:37 UTC, thelostone-mc approved these changes

2022-12-23 13:54 UTC, nfrgosselin requested changes
@vacekj I see this section of the page, and the days are updating correctly, but I don't see the contribution data:

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/15041635/209347180-c63e6d01-a92b-4e91-b3ea-d11518cadf3b.png">

2022-12-23 13:56 UTC, vacekj commented
@thelostone-mc do we have a live instance of the API running? This PR relies on it to display data, only the days will work without it.

2022-12-26 04:54 UTC, thelostone-mc commented
> @thelostone-mc do we have a live instance of the API running? This PR relies on it to display data, only the days will work without it.


It still looks like it's a WIP. @nfrgosselin to avoid the PR going stale -> I'm going to merge this in but keep the issue as blocked

2022-12-26 04:55 UTC, merged