feat: Save matching percentage to contract
gitcoinco/grants-round pull request #946
Opened 2023-01-06 12:38 UTC by bhargavaparoksham

##### Description

As a round operator
I want to finalize and store my fund distribution
So that my round results are public and verifiable

##### Refers/Fixes

fixes #869 

##### Testing

2023-01-06 14:17 UTC, thelostone-mc commented on packages/round-manager/src/features/api/round.ts
> +    console.error("finalizeRoindToContract", error);
```suggestion
    console.error("finalizeRoundToContract", error);
```

2023-01-11 00:48 UTC, vacekj commented
@bhargavaparoksham not sure how to finish up the redirect thing `ViewFundingAdmin.tsx:245` - we don't want to actually redirect no? Just show the view on EtherScan instead of the finalize button as per figma I think.

2023-01-11 11:32 UTC, thelostone-mc requested changes
Codewise LGTM but could we add in tests for FinalizeRoundContext as well ?

2023-01-11 12:37 UTC, melissa-neira commented
@bhargavaparoksham I'm not seeing the preview link for RM

2023-01-11 13:58 UTC, bhargavaparoksham commented
@melissa-neira please use the following link to preview / test it, https://bafybeihnuqcma4py2lkd4m3rlfwqwiv5hzc75bhh3tfi527dukog66qf3y.on.fleek.co/

2023-01-12 10:20 UTC, melissa-neira commented
Does anyone have a round that they've donated to so I can test this? I don't have any 😭 cc: @bhargavaparoksham @thelostone-mc

2023-01-12 13:03 UTC, thelostone-mc commented
Ah i don't have one either.
@nfrgosselin / @bhargavaparoksham would you be able to help out here?

2023-01-12 13:48 UTC, bhargavaparoksham commented
@melissa-neira @thelostone-mc unfortunately even i don't have round that has ended with active donations.

2023-01-13 11:11 UTC, bhargavaparoksham commented
@thelostone-mc tests for finalizeRoundContext has also been added now.

2023-01-16 13:41 UTC, closed without merging