feat: add finalized state to Funding Admin page
gitcoinco/grants-round pull request #968
Opened 2023-01-11 12:16 UTC by bhargavaparoksham

##### Description

As a round operator
I want to know what I finalized for my round
So that I can know when my round is closed

##### Refers/Fixes

fixes #893 

##### Testing

2023-01-18 14:04 UTC, thelostone-mc approved these changes

2023-01-18 16:14 UTC, melissa-neira requested changes
Functionally, it works great. There are a few UI elements I would like to change: 
- The box's corner radius should be 4px
- The box's header and "(2) Projects" should live inside the box.
- The "(2) Projects" text should be aligned more to the right. Right now it looks like it's floating and not really aligned to anything.
This is what it looks like currently:
![screencapture-bafybeieeys2ty6ae7b4ml3kq2n53m7gfx7empaj7usarwlk7ihvvloyxle-on-fleek-co-2023-01-18-17_03_50](https://user-images.githubusercontent.com/87520659/213227888-8e6b77f1-0470-4be0-8f37-dd768775b93c.png)
- the spacing between projects seems too big. let's make it smaller, more like this - [Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=3511%3A43461&t=XwUZf14VzrGOJTJl-4)

Sorry if this seems like a lot! I want to ensure this stays true to our design system as we have very similar boxes & content in Grants Hub.

I haven't finalized the round yet so I'll defer that to @nfrgosselin

2023-01-19 14:37 UTC, melissa-neira approved these changes

2023-01-19 18:53 UTC, nfrgosselin approved these changes

2023-01-19 18:53 UTC, merged